# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dpt_glasses',
            new_name='DptGlasses',
        ),
    ]
