# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_auto_20180109_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='dptglasses',
            name='type_glass',
            field=models.CharField(choices=[('dpt', 'з діоптріями'), ('frame', 'оправи'), ('sunglass', 'сонцезахисні'), ('computer', 'з комп. захистом'), ('drive', 'антифари'), ('other', 'інші')], default='dpt', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dptglasses',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='dptglasses',
            name='dpt',
            field=models.FloatField(blank=True, null=True, verbose_name='Діоптрії'),
        ),
        migrations.AlterField(
            model_name='dptglasses',
            name='kod',
            field=models.CharField(max_length=15, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='dptglasses',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='dptglasses',
            name='pcs',
            field=models.PositiveIntegerField(help_text='шт.', verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='dptglasses',
            name='price_opt',
            field=models.FloatField(help_text='грн', verbose_name='Оптова ціна'),
        ),
        migrations.AlterField(
            model_name='dptglasses',
            name='price_roz',
            field=models.IntegerField(help_text='грн', verbose_name='Роздрібна ціна'),
        ),
    ]
