# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0003_auto_20180130_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dptglasses',
            name='type_glass',
        ),
        migrations.AddField(
            model_name='dptglasses',
            name='glass_type',
            field=models.CharField(choices=[('dpt', 'з діоптріями'), ('frame', 'оправи'), ('sunglass', 'сонцезахисні'), ('computer', 'з комп. захистом'), ('drive', 'антифари'), ('others', 'інші')], default='dpt', max_length=20, verbose_name='Тип'),
        ),
    ]
