# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0004_auto_20180130_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DptGlasses',
            new_name='Glasses',
        ),
    ]
