# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldglasses',
            name='glass_type',
            field=models.CharField(default='dpt', max_length=20, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
